#!/bin/bash

	interfaces=("ppp" "ipoe" "dummy")


	mkdir -p /tmp/proc/net/

	while [  true ]; do
		cat /proc/net/dev | grep -v ${interfaces[@]/#/-e } > /tmp/proc/net/dev
		cat /proc/net/if_inet6 | grep -v ${interfaces[@]/#/-e } > /tmp/proc/net/if_inet6
		sleep 5
	done
